// 古着・中古服でよく出るブランドの表記ゆれ表。
//
// 中古サイトの出品タイトルは英字表記とカナ表記が混在するので、タグに書かれた
// 英字から日本語の通称を引けるようにしておく。検索語はカナのほうが当たりやすい。

export const BRANDS = [
  { canonical: "ノースフェイス", aliases: ["THE NORTH FACE", "NORTH FACE", "TNF"] },
  { canonical: "パタゴニア", aliases: ["PATAGONIA"] },
  { canonical: "アークテリクス", aliases: ["ARC'TERYX", "ARCTERYX", "ARC TERYX"] },
  { canonical: "コロンビア", aliases: ["COLUMBIA"] },
  { canonical: "モンベル", aliases: ["MONT-BELL", "MONTBELL", "MONT BELL"] },
  { canonical: "マムート", aliases: ["MAMMUT"] },
  { canonical: "グラミチ", aliases: ["GRAMICCI"] },
  { canonical: "スノーピーク", aliases: ["SNOW PEAK", "SNOWPEAK"] },
  { canonical: "カーハート", aliases: ["CARHARTT WIP", "CARHARTT"] },
  { canonical: "ディッキーズ", aliases: ["DICKIES"] },
  { canonical: "リーバイス", aliases: ["LEVI'S", "LEVIS", "LEVI STRAUSS"] },
  { canonical: "リー", aliases: ["LEE"] },
  { canonical: "ラングラー", aliases: ["WRANGLER"] },
  { canonical: "チャンピオン", aliases: ["CHAMPION"] },
  { canonical: "ナイキ", aliases: ["NIKE"] },
  { canonical: "アディダス", aliases: ["ADIDAS"] },
  { canonical: "プーマ", aliases: ["PUMA"] },
  { canonical: "リーボック", aliases: ["REEBOK"] },
  { canonical: "ニューバランス", aliases: ["NEW BALANCE"] },
  { canonical: "アシックス", aliases: ["ASICS"] },
  { canonical: "ミズノ", aliases: ["MIZUNO"] },
  { canonical: "バンズ", aliases: ["VANS"] },
  { canonical: "コンバース", aliases: ["CONVERSE"] },
  { canonical: "ラコステ", aliases: ["LACOSTE"] },
  { canonical: "フレッドペリー", aliases: ["FRED PERRY"] },
  { canonical: "ラルフローレン", aliases: ["POLO RALPH LAUREN", "RALPH LAUREN", "POLO BY RALPH LAUREN"] },
  { canonical: "トミーヒルフィガー", aliases: ["TOMMY HILFIGER", "TOMMY JEANS"] },
  { canonical: "カルバンクライン", aliases: ["CALVIN KLEIN"] },
  { canonical: "ギャップ", aliases: ["GAP"] },
  { canonical: "エディーバウアー", aliases: ["EDDIE BAUER"] },
  { canonical: "エルエルビーン", aliases: ["L.L.BEAN", "LL BEAN", "LLBEAN"] },
  { canonical: "ステューシー", aliases: ["STUSSY"] },
  { canonical: "シュプリーム", aliases: ["SUPREME"] },
  { canonical: "アベイシングエイプ", aliases: ["A BATHING APE", "BAPE"] },
  { canonical: "ヒューマンメイド", aliases: ["HUMAN MADE"] },
  { canonical: "ワコマリア", aliases: ["WACKO MARIA"] },
  { canonical: "ネイバーフッド", aliases: ["NEIGHBORHOOD"] },
  { canonical: "アンダーカバー", aliases: ["UNDERCOVER"] },
  { canonical: "ニードルス", aliases: ["NEEDLES"] },
  { canonical: "エンジニアドガーメンツ", aliases: ["ENGINEERED GARMENTS"] },
  { canonical: "ビズビム", aliases: ["VISVIM"] },
  { canonical: "サカイ", aliases: ["SACAI"] },
  { canonical: "コムデギャルソン", aliases: ["COMME DES GARCONS", "COMME DES GARÇONS"] },
  { canonical: "イッセイミヤケ", aliases: ["ISSEY MIYAKE"] },
  { canonical: "ヨウジヤマモト", aliases: ["YOHJI YAMAMOTO"] },
  { canonical: "オアスロウ", aliases: ["ORSLOW"] },
  { canonical: "リアルマッコイズ", aliases: ["THE REAL MCCOY'S", "REAL MCCOYS"] },
  { canonical: "バーバリー", aliases: ["BURBERRY"] },
  { canonical: "グッチ", aliases: ["GUCCI"] },
  { canonical: "プラダ", aliases: ["PRADA"] },
  { canonical: "ルイヴィトン", aliases: ["LOUIS VUITTON"] },
  { canonical: "シャネル", aliases: ["CHANEL"] },
  { canonical: "エルメス", aliases: ["HERMES", "HERMÈS"] },
  { canonical: "コーチ", aliases: ["COACH"] },
  { canonical: "ビームス", aliases: ["BEAMS"] },
  { canonical: "ユナイテッドアローズ", aliases: ["UNITED ARROWS"] },
  { canonical: "シップス", aliases: ["SHIPS"] },
  { canonical: "ナノユニバース", aliases: ["NANO UNIVERSE", "NANO・UNIVERSE"] },
  { canonical: "アーバンリサーチ", aliases: ["URBAN RESEARCH"] },
  { canonical: "ユニクロ", aliases: ["UNIQLO"] },
  { canonical: "ジーユー", aliases: ["GU"] },
  { canonical: "無印良品", aliases: ["MUJI"] },
];
